### PR TITLE
handle undefined operation

### LINKED ISSUE #206: Internal server error for some graphql-upload requests
## Description

We are currently using the graphql-upload package to add upload support to our graphql api, however for certain upload mutations we are receiving the error below which prevents the upload from succeeding. Disabling the newrelic addin solves the issue however that isn't a solution we want to consider in our production environment.

**Example request**
```
POST https://xxxxx.com/ HTTP/1.1
Content-Type: multipart/form-data; boundary="ef0e2df4-f746-4871-a349-4634341a5a24"
Host: xxxx.com
Content-Length: 131811
Expect: 100-continue

--ef0e2df4-f746-4871-a349-4634341a5a24
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name="operations"


{
    "operationName": "uploadDocument",
    "query": "\r\nmutation($file: Upload!) \r\n{\r\n    upload(input : {file: $file})\r\n    {\r\n        code, \r\n        error,\r\n        message,\r\n        uniqueId\r\n    }\r\n}"
}

--ef0e2df4-f746-4871-a349-4634341a5a24
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name="map"

{"file":["variables.file"] }
--ef0e2df4-f746-4871-a349-4634341a5a24
Content-Disposition: form-data; name="file"; filename="TST-101349-1384.pdf"
Content-Type: application/pdf

%PDF-1.4
%    
...
```

**Errror**
```
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'selectionSet')",
      "extensions":
      {
        "code": "INTERNAL_SERVER_ERROR",
        "exception":
        {
          "stacktrace": ["TypeError: Cannot read properties of undefined (reading 'selectionSet')", "    at isIntrospectionQuery (/node_modules/@newrelic/apollo-server-plugin/lib/create-plugin.js:461:20)", "    at shouldIgnoreTransaction (/node_modules/@newrelic/apollo-server-plugin/lib/create-plugin.js:476:46)", "    at Object.didResolveOperation (/node_modules/@newrelic/apollo-server-plugin/lib/create-plugin.js:105:15)", "    at /node_modules/apollo-server-core/dist/utils/dispatcher.js:21:31", "    at Array.map (<anonymous>)", "    at Dispatcher.callTargets (/node_modules/apollo-server-core/dist/utils/dispatcher.js:18:24)", "    at Dispatcher.<anonymous> (/node_modules/apollo-server-core/dist/utils/dispatcher.js:27:43)", "    at Generator.next (<anonymous>)", "    at /node_modules/apollo-server-core/dist/utils/dispatcher.js:8:71", "    at new Promise (<anonymous>)"]
        }
      }
    }
  ]
}
```

## Expected Behavior

The newrelic plugin shouldn't throw an error - it should ensure that any errors are captured and logged and not bubbled up to the calling application.

## Steps to Reproduce

See steps above in the description

## Your Environment

node 16.15
"@newrelic/apollo-server-plugin": "^1.3.0",
"apollo-server": "^3.8.1",
"graphql": "^15.5.0",
graphql-upload": "^13.0.0",
"newrelic": "^8.12.0",

## Additional context

I have raised a PR to prevent the error from occurring, see: 
https://github.com/newrelic/newrelic-node-apollo-server-plugin/pull/205

### PR DESCRIPTION
**Pull request by philjt**
## Proposed Release Notes
 * Added defensive code to prevent plugin from masking actual graphql errors.

## Links
Closes #206 

## Details
We are currently using the newrelic addin for apollo graphql along with the graphql-upload package to support file uploads via our graphql api.

For some upload requests we are receiving an error from the newrelic plugin that is preventing the upload request from continuing/completing.

Upon investigating the issue, is seems to be caused due to the "operation" being undefined within the newrelic plugin for these requests. The current plugin code doesn't have guards to consider this scenario resulting in an unhandled error.

**Example GQL Request:**
```
mutation($file: Upload!)
{
    upload(input : {file: $file})
    {
        code,
        error,
        message,
        uniqueId
    }
}
```
**Example Response**
```
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'selectionSet')",
      "extensions":
      {
        "code": "INTERNAL_SERVER_ERROR",
        "exception":
        {
          "stacktrace": ["TypeError: Cannot read properties of undefined (reading 'selectionSet')", "    at isIntrospectionQuery (/node_modules/@newrelic/apollo-server-plugin/lib/create-plugin.js:461:20)", "    at shouldIgnoreTransaction (/node_modules/@newrelic/apollo-server-plugin/lib/create-plugin.js:476:46)", "    at Object.didResolveOperation (/node_modules/@newrelic/apollo-server-plugin/lib/create-plugin.js:105:15)", "    at /node_modules/apollo-server-core/dist/utils/dispatcher.js:21:31", "    at Array.map (<anonymous>)", "    at Dispatcher.callTargets (/node_modules/apollo-server-core/dist/utils/dispatcher.js:18:24)", "    at Dispatcher.<anonymous> (/node_modules/apollo-server-core/dist/utils/dispatcher.js:27:43)", "    at Generator.next (<anonymous>)", "    at /node_modules/apollo-server-core/dist/utils/dispatcher.js:8:71", "    at new Promise (<anonymous>)"]
        }
      }
    }
  ]
}
```

### CODE REVIEW

**Comment by bizob2828** [comment]
@philjt Thanks for your PR. I'm going to take time trying to reproduce your issue so I can see how easy it'd be to add as a test.

**Comment by philjt** [comment]
@bizob2828 I have had another play with the code today and I can now replicate the issue running your example.

The key difference seems to be that the request fails when including an operationName in the request

This request succeeds
`curl --location --request POST 'http://localhost:29506/graphql' \ --form 'operations="{\"query\": \"mutation ($file: Upload!) { singleUpload(file: $file) { filename } }\", \"variables\": { \"file\": null } }"' \ --form 'map="{ \"0\": [\"variables.file\"] }"' \ --form '0=@"./Test Invoice.pdf"'`

However this one fails:
`curl --location --request POST 'http://localhost:29506/graphql' \ --form 'operations="{\"operationName\":\"testUpload\", \"query\": \"mutation ($file: Upload!) { singleUpload(file: $file) { filename } }\", \"variables\": { \"file\": null } }"' \ --form 'map="{ \"0\": [\"variables.file\"] }"' \ --form '0=@"./Test Invoice.pdf"'`

Note that the only difference is the inclusion of the operationName
curl --location --request POST 'http://localhost:29506/graphql'
--form 'operations="{**"operationName":"testUpload",** "query": "mutation ($file: Upload!) { singleUpload(file: $file) { filename } }", "variables": { "file": null } }"'
--form 'map="{ "0": ["variables.file"] }"'
--form '0=@"./Test Invoice - Copy (6).pdf"'

I hope this enables you also to replicate the issue.

Thanks

**Comment by bizob2828** [comment]
@philjt when I supply operationName I get an error from graphql, not our plugin:

```
{"errors":[{"message":"Unknown operation named \"testUpload\".","extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["GraphQLError: Unknown operation named \"testUpload\".","    at buildExecutionContext (/Users/revans/code/graphql-upload-node-16/node_modules/graphql/execution/execute.js:264:9)","    at execute (/Users/revans/code/graphql-upload-node-16/node_modules/graphql/execution/execute.js:116:22)","    at execute (/Users/revans/code/graphql-upload-node-16/node_modules/apollo-server-core/dist/requestPipeline.js:205:48)","    at processGraphQLRequest (/Users/revans/code/graphql-upload-node-16/node_modules/apollo-server-core/dist/requestPipeline.js:148:34)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async processHTTPRequest (/Users/revans/code/graphql-upload-node-16/node_modules/apollo-server-core/dist/runHttpQuery.js:220:30)"]}}}]}
```

**Comment by bizob2828** [comment]
Interesting, if I have the debug console opened the issue does not exist but if I just run the server I can repro.  I'd like to propose an alternate fix and add a unit test for this. I'll commit it shortly

**Review by bizob2828 — APPROVED** [review]

**Review by jordigh — APPROVED** [review]
I'm glad the logic could be simplified to a single chokepoint, the two tests seem comprehensive enough.

**Comment by philjt** [comment]
I have just signed the SLA.

**Comment by jordigh** [comment]
Thanks, this will be part of the next release, which should come out shortly.

**Comment by bizob2828** [comment]
@philjt let me know if v2.0.1 of plugin doesn't fix your issue.

**Pull request merged**
